[project]
name = "talktomydocsrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.3.30",
    "langchain-openai>=0.3.34",
    "pandas>=2.3.3",
    "tabulate>=0.9.0",
]
